package com.wireless.db;

import java.sql.SQLException;
import java.sql.Statement;

import com.wireless.exception.BusinessException;
import com.wireless.protocol.ErrorCode;
import com.wireless.protocol.Table;

public class InsertTable {
	
	/**
	 * Insert a new table record to database.
	 * @param table
	 * 			the table to be inserted
	 * @return
	 * 			the id generated by the database to this table record
	 * @throws BusinessException
	 * 			throws if either of cases below.<br>
	 * 			- The table id to be inserted has exist before.<br>
	 * 			- Fail to generate the id for this table record.
	 * @throws SQLException
	 * 			throws if fail to execute any SQL statement
	 */
	public static int exec(Table table) throws BusinessException, SQLException{
		DBCon dbCon = new DBCon();
		try{
			dbCon.connect();
			return exec(dbCon, table);
		}finally{
			dbCon.disconnect();
		}
	}
	
	/**
	 * Insert a new table record to database.
	 * Note that the database should be connected before invoking this method.
	 * @param dbCon
	 * 			the database connection
	 * @param table
	 * 			the table to be inserted
	 * @return
	 * 			the id generated by the database to this table record
	 * @throws BusinessException
	 * 			throws if either of cases below.<br>
	 * 			- The table id to be inserted has exist before.<br>
	 * 			- Fail to generate the id for this table record.
	 * @throws SQLException
	 * 			throws if fail to execute any SQL statement
	 */
	public static int exec(DBCon dbCon, Table table, boolean autoGenID) throws BusinessException, SQLException{

		String sql = "SELECT id FROM " + Params.dbName + 
					 ".table WHERE alias_id=" + table.alias_id +
					 " AND restaurant_id=" + table.restaurant_id;
		dbCon.rs = dbCon.stmt.executeQuery(sql);
		if(dbCon.rs.next()){
			throw new BusinessException("Table(alias_id=" + table.alias_id + ") has exist.", ErrorCode.TABLE_EXIST);
			
		}else{
			sql = "INSERT INTO " + Params.dbName + 
				  ".table (`id`, `alias_id`, `restaurant_id`, `name`) VALUES (" +
				  "NULL, " +
				  table.alias_id + ", " +
				  table.restaurant_id + ", '" +
				  (table.name != null ? table.name : "") + "'" +
				  ")";
			dbCon.stmt.execute(sql, Statement.RETURN_GENERATED_KEYS);
			//get the generated id to this new table 
			dbCon.rs = dbCon.stmt.getGeneratedKeys();
			if(dbCon.rs.next()){
				return dbCon.rs.getInt(1);
			}else{
				throw new BusinessException("The id of new table is not generated successfully.");
			}
		}
	}
}
