package com.wireless.db.frontBusiness;

import java.sql.SQLException;

import com.wireless.db.DBCon;
import com.wireless.db.Params;
import com.wireless.exception.BusinessException;
import com.wireless.exception.ProtocolError;
import com.wireless.protocol.PTable;
import com.wireless.protocol.Terminal;

public class InsertTable {
	
	/**
	 * Insert a new table record to database.
	 * @param pin
	 *            the pin to terminal
	 * @param model
	 *            the model to terminal
	 * @param table
	 * 			the table to be inserted
	 * @param autoGenID
	 * 			indicating generate table alias id automatically or using the Table parameter
	 * @return
	 * 			the id generated by the database to this table record
	 * @throws BusinessException
	 * 			throws if either of cases below.<br>
 	 *	 		- The terminal is NOT attached with any restaurant.<br>
	 *			- The terminal is expired.<br>
	 * 			- The table id to be inserted has exist before.<br>
	 * 			- Fail to generate the id for this table record.
	 * @throws SQLException
	 * 			throws if fail to execute any SQL statement
	 */
	public static PTable exec(long pin, short model, PTable table, boolean autoGenID) throws BusinessException, SQLException{
		DBCon dbCon = new DBCon();
		try{
			dbCon.connect();
			return exec(dbCon, pin, model, table, autoGenID);
		}finally{
			dbCon.disconnect();
		}
	}
	
	/**
	 * Insert a new table record to database.
	 * Note that the database should be connected before invoking this method.
	 * @param dbCon
	 * 			the database connection
	 * @param pin
	 *            the pin to terminal
	 * @param model
	 *            the model to terminal
	 * @param table
	 * 			the table to be inserted
	 * @param autoGenID
	 * 			indicating generate table alias id automatically or using the Table parameter
	 * @return Table
	 * 			the new table generated by the database to this table record
	 * @throws BusinessException
	 * 			throws if either of cases below.<br>
	 * 			- The terminal is NOT attached with any restaurant.<br>
	 *			- The terminal is expired.<br>
	 * 			- The table id to be inserted has exist before.<br>
	 * 			- Fail to generate the id for this table record.
	 * @throws SQLException
	 * 			throws if fail to execute any SQL statement
	 */
	public static PTable exec(DBCon dbCon, long pin, short model, PTable table, boolean autoGenID) throws BusinessException, SQLException{
		return exec(dbCon, VerifyPin.exec(dbCon, pin, model), table, autoGenID);		
	}
	
	public static PTable exec(DBCon dbCon, Terminal term, PTable table, boolean autoGenID) throws BusinessException, SQLException{
		
		PTable newTbl = new PTable();
		newTbl.setAliasId(table.getAliasId());
		newTbl.setName(table.getName());
		newTbl.setRestaurantId(term.restaurantID);
		newTbl.setStatus(PTable.TABLE_IDLE);
		newTbl.setCategory(PTable.TABLE_NORMAL);
		
		String sql;
		if(autoGenID){
			
			sql = "SELECT MAX(table_alias) + 1 FROM " + Params.dbName + ".table WHERE restaurant_id=" + term.restaurantID;
			dbCon.rs = dbCon.stmt.executeQuery(sql);
			if(dbCon.rs.next()){
				newTbl.setAliasId(dbCon.rs.getInt(1));
			}else{
				throw new BusinessException("Fail to generate the table alias id.");
			}
			dbCon.rs.close();
			
		}else{
			sql = "SELECT id FROM " + Params.dbName + 
				  ".table WHERE " +
				  "restaurant_id=" + term.restaurantID + 
				  " AND " +
				  "table_alias=" + newTbl.getAliasId();
			dbCon.rs = dbCon.stmt.executeQuery(sql);
			if(dbCon.rs.next()){
				throw new BusinessException("Table(alias_id=" + newTbl.getAliasId() + ", restaurant_id=" + term.restaurantID + ") is exist.", ProtocolError.TABLE_EXIST);
			}	
			dbCon.rs.close();
		}

		/**
		 * If set to auto generate table alias id, the alias id would be set to current maximum id value plus one.
		 * Otherwise, set the alias id using the parameter pass into the function. 
		 */
		sql = "INSERT INTO " + Params.dbName + 
			  ".table (`table_id`, `table_alias`, `restaurant_id`, `name`, `category`, `custom_num`, `status`) VALUES( " +
			  "NULL, " +
			  newTbl.getAliasId() + ", " +
			  term.restaurantID + ", '" +
			  (newTbl.getName() != null ? newTbl.getName() : "") + "', " + 
			  "NULL, " +
			  "NULL, " +
			  PTable.TABLE_IDLE +
			  ")";
		
		dbCon.stmt.execute(sql);
		
		return newTbl;
	}
	
}
